### ISSUE TITLE
it doesn't work in electron

### ISSUE THREAD

**Issue by ChurchTao** [paymoapp/node-active-window#2]
I can run your demo normally
But when I run it in the electron main thread

```
import ActiveWindow, { WindowInfo } from '@paymoapp/active-window'
app.whenReady().then(() => {
  ActiveWindow.initialize({ osxRunLoop: true })
  ActiveWindow.requestPermissions()
})
```

```
(node:56708) UnhandledPromiseRejectionWarning: TypeError: ActiveWindow.initialize is not a function
```

**Comment by gergof** [comment]
Hi! Could you please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?
A git repo with your setup would be sufficient only containing your build setup and electron main. 

It is probably some kind bundling error. If you use vite (or webpack or anything else), you have to explicitly exclude the library from the bundle (since it contains native code that should be loaded directly by node). To do this in vite for example you have to define the library as an external module (`build.rollupOptions.external`).

Also: Since you're using electron (and hence have a GUI window on the main thread with a working runloop), you can omit the osxRunLoop parameter (see: https://github.com/paymoapp/node-active-window#%F0%9D%91%93--initialize)

**Comment by ChurchTao** [comment]
Thank you for your reply. I do use Vite. I will try it again based on your suggestion. If there are still any problems, I will report back.

**Comment by ChurchTao** [comment]
> Hi! Could you please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? A git repo with your setup would be sufficient only containing your build setup and electron main.
> 
> It is probably some kind bundling error. If you use vite (or webpack or anything else), you have to explicitly exclude the library from the bundle (since it contains native code that should be loaded directly by node). To do this in vite for example you have to define the library as an external module (`build.rollupOptions.external`).
> 
> Also: Since you're using electron (and hence have a GUI window on the main thread with a working runloop), you can omit the osxRunLoop parameter (see: https://github.com/paymoapp/node-active-window#%F0%9D%91%93--initialize)

minimal reproducible example:
https://github.com/ChurchTao/electron-active-window-demo

I tried again, and it really didn’t work. It seemed like the method was exported to npm incorrectly, and the real method could not be referenced.

**Comment by ChurchTao** [comment]
<img width="807" alt="image" src="https://github.com/paymoapp/node-active-window/assets/19499577/2187173b-91e0-45da-85aa-1a45d7d6cc7e">
When I click on the method in the compiled js, I cannot jump to the actual calling location.

**Comment by gergof** [comment]
I had some time to check out your repo and found the problem. There is a problem with esbuild (the bundler used by vite) about how it handles the default imports of CJS modules.

The library was accessible in your case, but you would have to use `ActiveWindow.default.initialize()` because of this.

To fix this, you have to go to your vite config and in the main section you have to add `build.rollupOptions.output.interop = 'auto'`.

I've updated the config you provided in your example repo:
```js
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        output: {
          interop: 'auto'
        }
      }
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    plugins: [react()]
  }
})
```

For more info see: https://rollupjs.org/configuration-options/#output-interop
