### ISSUE TITLE
Possibility of URL tracking

### ISSUE THREAD

**Issue by Srini-B** [paymoapp/node-active-window#3]
Hi, Thanks for the package, will it be possible to get URL is the active window is browser. Close the issue at your continence. I plan to use this in an electron app

**Comment by gergof** [comment]
Hi @Srini-B !
This would only be possible on MacOS using applescript. I don't plan on implementing this one into the library since it can be done easily using other packages when you detect a browser as the frontmost application.

For example using https://www.npmjs.com/package/run-applescript you could execute `tell app id "${appId}" to get the URL of active tab of front window`.
